project:
  type: book

book:
  title: "Getting Started With Parkinson's Disease Data"
  author:
    - name: "Michael Alosco"
      affiliation: "Boston University Chobanian & Avedisian School of Medicine"
    - name: "Elizabeth Hutchins"
      affiliation: "TGen/DataTecnica/NIH CARD"
    - name: "Paula Saffie Awad"
      affiliation: "CETRAM/Clinica Santa Maria"
    - name: "Victoria Dardov"
      affiliation: "Technome"
    - name: "Joshua Gottesman"
      affiliation: "The Michael J. Fox Foundation"
    - name: "Hirotaka Iwaki"
      affiliation: "NIH CARD/NIA/DataTecnica"
    - name: "Paula Reyes-Perez"
      affiliation: "UNAM"
    - name: "Daniel Teixeira dos Santos"
      affiliation: "Hospital de Clinicas de Porto Alegre"
    - name: "Maya Sanghvi"
      affiliation: "The Center for Scientific Collaboration and Community Engagement"
  date: "2024-05-01"
  version: "1.0"
  repo-url: https://github.com/MJFF-ResearchCommunity/getting-started-PD-data
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - overview.qmd
    - amp-pd.qmd
    - ppmi.qmd
    - gp2.qmd
    - fox-insight.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    link-external-icon: true
    link-external-newwindow: true
